version: "3"    
    
services:

  database:
     
    image: mysql:5.6
    container_name: database
    networks:
      - wpnet
    volumes:
      - database-mysql:/var/lib/mysql/
    environment:
        
      - MYSQL_ROOT_PASSWORD=t33th123!
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wpuser@123
    
  wordpress:
    
    image: wordpress:latest
    container_name: wordpress
    networks:
      - wpnet
    volumes:
      - wordpress-data:/var/www/html/
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wpuser@123
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "8080:80"
    
  phpmyadmin:

    image: phpmyadmin/phpmyadmin
    container_name: wpphpmyadmin
    restart: always
    networks:
      - wpnet
    ports:
      - '8000:80'
    environment:
      - PMA_HOST:database
      - MYSQL_ROOT_PASSWORD:t33th123!
    depends_on:
      - database      


networks:
  
  wpnet:
        
    
volumes:
    
  database-mysql:
  wordpress-data:
